### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by RaviPabari** [silktown-software/podbean_downloader#4]
Please provide some usage examples

**Comment by silktown-software** [comment]
I'll add some instructions to the wiki. this weekend.

**Comment by RaviPabari** [comment]
Hii any updates?

**Comment by silktown-software** [comment]
Sorry this is later than promised. I've updated the README. It now shows:

1) How to make the setup tools script.
2) How to install it as a user script using `pip`
3) Basic usage.

**Comment by RaviPabari** [comment]
No worries thanks for the update.
