### ISSUE TITLE
url_collection empty

### ISSUE THREAD

**Issue by RaviPabari** [silktown-software/podbean_downloader#5]
`url_collection = [link.get('href') for link in soup.find_all('a', {'class': 'btn-playnow'})]`
line 19 in downloader.py, url_collection is empty, program breaks at that point.

**Comment by silktown-software** [comment]
I will have a look at the weekend. I forgot RSS feeds exists when I made this for a friend last year.

**Comment by silktown-software** [comment]
I tried it with a creator page and it works fine. It just doesn't do anything if you use the other listings on their site.

I will just get the script to detect an RSS feed I think and use that and use scraping as a last resort.

**Comment by RaviPabari** [comment]
I want to download podcast from this url ```https://neilbhatt.podbean.com/``` is this valid link? . Can you have a look, currently it only prints url/page-number and ends
![image](https://user-images.githubusercontent.com/46424422/135738852-59c1a3a5-f16f-402b-9bae-25dd1989535d.png)

**Comment by silktown-software** [comment]
Thanks for the information. I had a look at the page and a the structure was totally different than the page I built the downloader for :open_mouth:. There seems to be two types of creator pages. If I get time this weekend, I think the strategy is to do the following:

1) Try finding the download page from either types of page. 
2) From there you can find the episode list.
3) Find the episode list url and the use that to page through.
4) If all else fails just use the RSS feed.

That should work I think.

**Comment by RaviPabari** [comment]
Got it. Thanks for the update. And I am also working on one solution for
the type of link I earlier mentioned.

**Comment by silktown-software** [comment]
This is probably a little late now. But I've reworked the downloader so it works on these pages now.

**Comment by RaviPabari** [comment]
> This is probably a little late now. But I've reworked the downloader so it works on these pages now.

Cool! will surely check it out. Also in meantime I had worked on the same and implemented a solution that works for those pages. Have a look https://github.com/RaviPabari/podbean_downloader
